[WIP] Added new tool - expressive-module (#8 and #9)
zendframework/zend-expressive-tooling pull request #12
Opened 2017-02-17 16:14 UTC by webimpress

New tool `vendor/bin/expressive-module`

Tool provide following commands:
- `create` - create skeleton of the expressive module and register it
- `register` - register module in configuration and composer autoloading
- `deregister` - deregister module from configuration and composer autoloading

Tool accept following arguments:
- `--composer|-c` path to composer binary
- `--modules-path|-p` - path to modules directory

TODO:
- [ ] tests
  - [ ] create
  - [ ] register
  - [ ] deregister
- [ ] implement deregister form composer autoloading - will be nice to have it in [`zfcampus/zf-composer-autoloading`](https://github.com/zfcampus/zf-composer-autoloading) as there is also registering module in composer.json
- [ ] would be nice to refactor [`zendframework/zend-component-installer`](https://github.com/zendframework/zend-component-installer) then we can have here less dependencies - now because we are using this library we require here `composer/composer`.

Resolves #8 and #9

2017-02-17 17:43 UTC, weierophinney commented
Syntax is perfect - exactly what I'd expect! Looking forward to reviewing the final iterations!

2017-02-22 17:32 UTC, webimpress commented
@weierophinney It's ready for review, tests are failing but some of them are fixed in #10, so it should be merged first. Of course it needs also `zend-component-install 0.7.0` release and update requirements in `composer.json`.
What is missing here - messages on success. Now we don't have any messages, so it's confusing if it was done successfully or not. Just response code is 0 on success. I need to think about it a bit more how to do it nicely, or maybe you have an idea?

2017-02-22 17:59 UTC, weierophinney commented
@webimpress I've tagged zend-component-installer 0.7.0 at this time, and merged #10.

As for messages, how about:

- "Created module `<module name>` in `<path>`, and generated autoloading rules"
- "Registered autoloading rules and added configuration entry for module `<module>`"
- "Removed autoloading rules and configuration entries for module `<module>`"

2017-02-22 22:32 UTC, webimpress commented
@weierophinney Rebased, used latest stable dependencies and added success messages as suggested. Ready for review.

2017-03-01 15:07 UTC, weierophinney requested changes
Looks fantastic, @webimpress ! There are a few minor changes I've suggested, and one larger one that, honestly, I can go either way on (whether or not to memorize `$modulePath`). Let me know how you want to proceed on that, and I can merge.

2017-03-01 15:07 UTC, weierophinney commented on composer.json
> +        "bin/expressive-module"
These should be alphabetized.

2017-03-01 15:07 UTC, weierophinney commented on src/Module/Command/Create.php
> + * @see https://docs.zendframework.com/zend-component-installer/
Nice touch! Linking to the documentation will definitely assist new developers.

2017-03-01 15:07 UTC, weierophinney commented on src/Module/Command/Create.php
> +        if (file_exists($this->modulePath)) {
Considering that `$modulePath` is calculated by `process()`, perhaps it should be passed as an argument to each of this method and `createConfigProvider()`, instead of memoized as a property? That would be one less state for the instance to track.

2017-03-01 15:07 UTC, weierophinney commented on src/Module/Help.php
> +  <info>create</info>        Create skeleton of the expressive module and register it
`s/skeleton of/source tree for/`

2017-03-01 15:07 UTC, weierophinney commented on src/Module/Help.php
> +  <info>register</info>      Register module in configuration and composer autoloading
"Register module in application configuration, and enable autoloading of module via composer."

2017-03-01 15:07 UTC, weierophinney commented on src/Module/Help.php
> +  <info>deregister</info>    Deregister module from configuration and composer autoloading
"Deregister module from application configuration, and disable autoloading of module via composer."

2017-03-01 15:07 UTC, weierophinney commented on test/Module/Command/CreateTest.php
> +        $mkdir = $this->getFunctionMock('Zend\Expressive\Tooling\Module\Command', 'mkdir');
I was not aware of `getFunctionMock()`! Awesome!

2017-03-01 15:07 UTC, weierophinney commented on test/Module/Command/DeregisterTest.php
> +use Mockery\Adapter\Phpunit\MockeryPHPUnitIntegration;
Is this what allows you to not need to specify `@runInSeparateProcess` for tests that overload classes via Mockery?

2017-03-01 15:42 UTC, webimpress commented on test/Module/Command/CreateTest.php
> +        $mkdir = $this->getFunctionMock('Zend\Expressive\Tooling\Module\Command', 'mkdir');
Please not this is _not_ from PHPUnit but from `php-mock` library. Integration with PHPUnit is via `php-mock/php-mock-phpunit`.

2017-03-01 15:48 UTC, webimpress commented on test/Module/Command/DeregisterTest.php
> +use Mockery\Adapter\Phpunit\MockeryPHPUnitIntegration;
Hm... this is recommended in Mockery documentation:
http://docs.mockery.io/en/latest/reference/phpunit_integration.html

I was trying to remove `@runInSeparateProcess` but some tests on some versions (php versions/dependencies) were failing. As you can note in some tests we still have this annotation.

2017-03-01 15:49 UTC, webimpress commented on src/Module/Command/Create.php
> +        if (file_exists($this->modulePath)) {
Changed - property removed, now method has two parameters.

2017-03-01 16:32 UTC, weierophinney commented on test/Module/Command/CreateTest.php
> +        $mkdir = $this->getFunctionMock('Zend\Expressive\Tooling\Module\Command', 'mkdir');
Ah, okay - did you add that dependency, or does PHPUnit depend on it itself? Either way, it's a nice library to know about.

2017-03-01 16:32 UTC, weierophinney commented on test/Module/Command/DeregisterTest.php
> +use Mockery\Adapter\Phpunit\MockeryPHPUnitIntegration;
I've somehow missed that documentation page previously, so, again, a nice thing to know about!

2017-03-01 16:33 UTC, weierophinney approved these changes
Changes look perfect! Thanks, @webimpress !

2017-03-01 16:46 UTC, webimpress commented on test/Module/Command/CreateTest.php
> +        $mkdir = $this->getFunctionMock('Zend\Expressive\Tooling\Module\Command', 'mkdir');
Yes, I added:
```json
"php-mock/php-mock-phpunit": "^2.0 || ^1.1.2",
```
There is also integration library with prophecy and mocker.
https://github.com/php-mock
I've chosen integration with PHPUnit as this is the main testing library. I know that many mocking we are doing recently using prophecy, so maybe better choice will be `php-mock-prophecy`?
Here is the library with the main functionality:
https://github.com/php-mock/php-mock

2017-03-01 16:53 UTC, merged