Migrate interop middlewares tool updated to final PSR-15
zendframework/zend-expressive-tooling pull request #44
Opened 2018-01-23 10:01 UTC by webimpress

It migrates now all kind of interop middlewares

2018-01-23 10:33 UTC, geerteltink requested changes
Please fix import order in all test classes and change the date range :D

2018-01-23 10:39 UTC, webimpress commented
@xtreamwayz it will be very hard to change order of imports there - please note these are TestAssets, and the tool is replacing interfaces with proper PSR-15 interfaces.

About date range... Yeh... I can update it, but I would prefer to remove these headers and year from header at all then updating it every year. Hopefully we will have soon zend-coding-standard in place and we can get rid of these headers for ever!

2018-01-23 10:50 UTC, geerteltink approved these changes

2018-02-06 22:25 UTC, merged

2018-02-06 22:26 UTC, weierophinney commented
Thanks, @webimpress!