Added new command migrate:middleware-to-request-handler
zendframework/zend-expressive-tooling pull request #58
Opened 2018-02-15 09:07 UTC by webimpress

Convert PSR-15 middleware to request handler in given path. It should be used to convert final middlewres binded to routes which are not using delegator/request handler.

Works only with PSR-15 middlewares (if you have interop middlewares migrate them first to PSR-15 middlewares by migrate:interop-middleware and then convert them to request handlers).

2018-02-15 15:39 UTC, weierophinney commented
I would argue that this should raise an exception if it detects any `$handler->handle` calls.

2018-02-15 16:00 UTC, webimpress commented
@weierophinney 
> I would argue that this should raise an exception if it detects any $handler->handle calls.

2018-02-19 02:31 UTC, weierophinney requested changes

2018-02-19 02:31 UTC, weierophinney commented on test/MigrateMiddlewareToRequestHandler/TestAsset/expected/MyMiddlewareWithHandler.php
> +
We need a license docblock here and on the other test asset; we should likely also add the `declare(strict_types=1)`, though that's not completely necessary.

2018-02-21 21:22 UTC, merged

2018-02-21 21:22 UTC, weierophinney commented
Thanks, @webimpress!