Bugfix/config-array
zendframework/zend-expressive-tooling pull request #89
Opened 2019-05-21 22:11 UTC by jakejohns

### Detail how the bug is invoked currently.
- `$ composer create-project zendframework/zend-expressive-skeleton expressive`
- Select `Aura\Di` as the container
- `$ composer expressive action:create "App\FooBar"`
```
PHP Fatal error:  Uncaught TypeError: Return value of
Zend\Expressive\Tooling\CreateHandler\CreateTemplate::getConfig() must be of the
type array, object returned [...] /ConfigAndContainerTrait.php:37
```

### Detail the original, incorrect behavior.
[Aura\Di uses an ArrayObject][ArrayObject] for the `config` key. Returning it
from this method with a return type of `array` produces an error.

### Detail the new, expected behavior.
This just casts the value to an array `return (array) [...]`
Alternatively we could:
- Change the return type
- Check if it's an `ArrayObject` and call `getArrayCopy()`
- Something else

[ArrayObject]: https://github.com/zendframework/zend-auradi-config/blob/1c8295d3f698a630909b6eeb57b7009af2479fae/src/Config.php#L65

2019-05-21 23:14 UTC, Xerkus commented
I think something like this would be more reliable:
```
$config = $container->get('config');
if (is_array($config)) {
    return $config;
}
if (! $config instanceof Traversable) {
    throw ...
}
return iterator_to_array($config);
```

2019-05-22 14:50 UTC, weierophinney commented
I agree with @Xerkus . Additionally, we'll need a unit test for this to ensure we don't remove that code in the future, and thus break something that was working.

2019-05-22 16:47 UTC, jakejohns commented
Feelings on the type of exception or message?
```php
throw new \InvalidArgumentException(
    '"config" service must be an array or instance of Traversable'
);
```

2019-05-22 16:47 UTC, jakejohns commented
Feelings on the type of exception or message?
```php
throw new \InvalidArgumentException(
    '"config" service must be an array or instance of Traversable'
);
```

2019-05-22 18:13 UTC, Xerkus requested changes
Also please import all global functions and classes. We use PSR-12 formatting for imports, separating into groups:
```
use Class;

use function;

use CONSTANT;
```

2019-05-22 18:13 UTC, Xerkus commented on src/ConfigAndContainerTrait.php
> +            throw new \InvalidArgumentException(
it is a runtime condition, so RuntimeException.
I would also suggest to improve message like so:
```php
sprintf(
    '"config" service must be an array or instance of ArrayObject or Traversable, got %s',
    is_object($config) ? get_class($object) : gettype($object)
);
```

2019-05-23 12:30 UTC, jakejohns commented
I'm really not sure where I'd add a test for this, unless making a new one.

2019-08-28 18:17 UTC, merged